aws_s3_bucket = "s3://splunk-apps-2024123456789"

[app]
    [app.Splunk_TA_nix]
    name = "Splunk_TA_nix"
    filename = "splunk-add-on-for-unix-and-linux_920.tgz"
    servers = "splunk-hf-*"

    [app.Splunk_TA_aws]
    name = "Splunk_TA_aws"
    filename = "splunk-add-on-for-amazon-web-services-aws_780.tgz"
    servers = "splunk-hf-1"

    [app.Splunk_TA_windows]
    name = "Splunk_TA_windows"
    filename = "splunk-add-on-for-microsoft-windows_901.tgz"
    servers = "splunk-hf-2"
